[colors.bright]
black = "#928374"
blue = "#458588"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#ebdbb2"
yellow = "#fabd2f"

[colors.normal]
black = "#282828"
blue = "#83a598"
cyan = "#689d6a"
green = "#98971a"
magenta = "#b16286"
red = "#cc241d"
white = "#a89984"
yellow = "#d79921"

[colors.primary]
background = "#282828"
foreground = "#ebdbb2"

#[font]
#size = 7.0

[font.bold]
family = "JetBrainsMono NF"
style = "Bold"

[font.normal]
family = "JetBrainsMono NF"
style = "Regular"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Alt|Shift"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Alt|Shift"

[[keyboard.bindings]]
key = "J"
mods = "Alt|Shift"
action = "ScrollPageDown"

[[keyboard.bindings]]
key = "K"
mods = "Alt|Shift"
action = "ScrollPageUp"

[[keyboard.bindings]]
key = "Enter"
mods = "Alt"
action = "ReceiveChar"

#[[key_bindings]]
#action = "Command"
#key = "A"
#mods = "Control|Shift"
#command = "alacritty msg config window.opacity 1.0"
#
#[[key_bindings]]
#action = "Command"
#key = "S"
#mods = "Control|Shift"
#command = "alacritty msg config window.opacity 0.8"
#
#[[key_bindings]]
#action = "Command"
#key = "L"
#mods = "Alt|Control"
#command = "/path/to/extract_links.sh"

[[keyboard.bindings]]
action = "ToggleMaximized"
#action = "ToggleFullscreen"
key = "F"
mods = "Alt|Shift"

[window]
#dimensions = { columns = 160, lines = 40 }
#position = "None"
position = { x = 50, y = 65 }
#decorations = "Full"
decorations = "None"
startup_mode =  "Maximized"
#startup_mode =  "Fullscreen"

#[window.padding]
#x = 13
#y = 13

# https://github.com/Piotr1215/dotfiles/blob/master/.config/alacritty/alacritty.toml
[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "Space", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

[[hints.enabled]]
regex = '[^ ]+(?:\s*)$' 
command = { program = "/usr/bin/tmux", args = ["split-window", "-h", "-c", "#{pane_current_path}", "sh", "-c", "nvim \"$0\""] }
binding = { key = "Space", mods = "Alt|Shift" }

