"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

# See:
# https://github.com/sxyazi/yazi/blob/main/yazi-config/preset/yazi-default.toml

[manager]
show_hidden = true
#sort_by = "modified"
sort_reverse = true
linemode = "mtime"

[opener]
edit = [
	{ run = '$EDITOR "$@"', block = true, for = "unix" },
	{ run = "%EDITOR% %*",  block = true, for = "windows" },
]

